DemoWebsite/Models/Login.cs
using System.ComponentModel.DataAnnotations;

namespace DemoWebsite.Models
{
    public class Login 
    {
        #region Properties
        [Key]
        /// <summary>
        /// There are no comments for email in the schema.
        /// </summary>
        public virtual string emailID
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for password in the schema.
        /// </summary>
        public virtual string password
        {
            get;
            set;
        }


        /// <summary>
        /// There are no comments for guid in the schema.
        /// </summary>
        public virtual string guid
        {
            get;
            set;
        }
        #endregion
    }
}

DemoWebsite/Models/ViewModel/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DemoWebsite.Models
{
   public class LoginViewModel
    {
        [Key]
        public int UserId { get; set; } 
               
        [Required(ErrorMessage = "Email ID shouldn't be Empty")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Enter valid Email Address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Enter Password.")]        
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
     

    }
}

DemoWebsite/Controllers/UsersLoginController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Microsoft.Owin.Security;
using DemoWebsite.Services;
using DemoWebsite.Models;
using System.Linq;

namespace DemoWebsite.Controllers
{
    //[Authorize]
    public class UsersLoginController : Controller
    {
        #region Members
        //private SparkTechDB unitOfWork;

        private readonly IUserService userService;
        private readonly ICartService cartService;

        public UsersLoginController(IUserService user, ICartService cart)
        {
            userService = user;
            cartService = cart;
        }

        private UserManager<ApplicationUser> userManager { get; set; }
        private IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
        #endregion Members
        

        #region Actions
        // GET: /UsersLogin/Login
        
        [AllowAnonymous]
        public ActionResult Login()
        {
            Session["HomePage"] = null;
            //var vmLogin = new UserRegistration
            //{
            //    ReturnUrl = returnUrl
            //};

            //return View(vmLogin);
            return View();
        }

        // POST: /UsersLogin/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(UserRegistration vmLogin)
        {
            #region Count the Cart Items
            //var session = System.Web.HttpContext.Current.Session;
            //int authenticateUserID = 0;
            //if (SessionUtilities.GetAuthenticatedUserId() == 0)
            //{
            //    session["CartItems"] = cartService.GetCartItems().Where(a => a.Status == "Pending" || a.Status == "NULL").Distinct().Count();
            //}
            //else
            //{
            //    authenticateUserID = SessionUtilities.GetAuthenticatedUserId();
            //    var userDetail = userService.GetUserDataByUserID(authenticateUserID);
            //    session["CartItems"] = cartService.GetCartItemsByEmailID(userDetail.Email).Where(a => a.Status == "Pending" || a.Status == "NULL").Distinct().Count();
            //}

            #endregion

            if (!ModelState.IsValid)
            {
                return View();
            }
            vmLogin.RememberMe = Convert.ToBoolean(Request.Form["rememberMe"]);
           
            var response = userService.CheckLogin(vmLogin);
            if (response.Response != null)
            {
                var identity = new ClaimsIdentity(new[]
                {
                    new Claim(ClaimTypes.Sid, Convert.ToString(response.Response.UserId)),
                    new Claim(ClaimTypes.Name, response.Response.FirstName+" "+response.Response.LastName),
                    new Claim(ClaimTypes.Email, response.Response.Email),
                    new Claim(ClaimTypes.Role, response.Response.Role)
                }, "ApplicationCookie");

                var ctx = Request.GetOwinContext();
                var authManager = ctx.Authentication;
                authManager.SignIn(identity);
                if (vmLogin.RememberMe)
                {
                    HttpCookie cookie = new HttpCookie("iShopUserLogin");
                    cookie.Values.Add("userEmail", vmLogin.Email);
                    cookie.Expires = DateTime.Now.AddDays(15);
                    Response.Cookies.Add(cookie);
                }

                cartService.updateCartDataInDb(vmLogin.Email);
                //LoginHistoryService.InsertLoginHistory(Convert.ToString(response.Response.UserId), iShop.Models.CommonEnums.UserType.User);                
                return RedirectToAction("Index", "Home");
                
            }
            else
            {
                // user authN failed
                TempData["Error"] = "Invalid User ! Please try again with correct Email Id/Password";
                return View();
            }
            
        }
        private string GetRedirectUrl(string returnUrl)
        {
            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
            {
                return Url.Action("Index", "Home");
            }

            return returnUrl;
        }

        public ActionResult LogOut()
        {
            var ctx = Request.GetOwinContext();
            var authManager = ctx.Authentication;
            authManager.SignOut("ApplicationCookie");
            System.Web.HttpContext.Current.Session["CartId"] = System.Web.HttpContext.Current.Session.SessionID;
            //LoginHistoryService.UpdateLogoutTime(iShopHelper.GetCurrentUserId(), iShop.Models.CommonEnums.UserType.User);
            return RedirectToAction("Index", "Home");
        }

        #endregion Actions
        #region DataTable
        #endregion DataTable

        #region Methods
        #endregion Methods
    }
}

DemoWebsite/Views/UsersLogin/Login.cshtml
@model DemoWebsite.Models.UserRegistration

<style>
    .error {
        font-size: 13px;
        margin-left: 10px;
    }
</style>

@using (Html.BeginForm("Login","UsersLogin",FormMethod.Post, new { id = "registerForm" }))
{
    <div class="rest-body">
        @Html.Partial("_Login", Model)
    </div>    
}

DemoWebsite/Views/UsersLogin/_Login.cshtml
@model DemoWebsite.Models.UserRegistration

@Html.AntiForgeryToken()
<div class="container">
    <fieldset>
        <legend>Login</legend>
    </fieldset>
    <div class="row">
       
        <div class="col-md-6 login-form">            
            <div class="form-group">
                <label for="email">Email Address</label>
                @Html.EditorFor(model => model.Email, "", new { htmlAttributes = new { @placeholder = "Email Address", @class = "form-control", id = "email" , tabindex = "1",type="email", required = "required" } })
            </div>
            <div class="form-group">
                <label for="InputPassword">Password</label>
                @Html.EditorFor(model => model.Password, "", new { htmlAttributes = new { @placeholder = "Password", @class = "form-control", id = "InputPassword", type = "password", tabindex = "2", required = "required" } })
            </div>
        </div>        
    </div>
    <button type="submit" class="btn btn-primary" tabindex="3" style="position:relative;left:47%;">Login</button><br>
    <span>Not yet Register? <a href="@Url.Action("Create","UserRegistrations")">Register Now</a></span>

<div id="snackbar" style="background-color: #F00;">Product added in cart..</div>

@if (TempData["Error"] != null)
{
    <script type="text/javascript">
        var messageForSnackBar = "@TempData["Error"]";
        $("#snackbar").text(messageForSnackBar);
        $("#snackbar").addClass("show");
        setTimeout(function () {
            $("#snackbar").removeClass("show");
        }, 9000);        
    </script>        
}