DemoWebsite/Models/UserRegistration.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DemoWebsite.Models
{
  public class UserRegistration
    {

        // Change when run migration
        [Key]
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
              
        public string PhoneNumber { get; set; }
               
        public string Password { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string Role { get; set; }
        public string Status { get; set; }
        public bool RememberMe { get; set; }
        public DateTime? LastLogin { get; set; }        

    }
}

DemoWebsite/Controllers/UserRegistrationsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Security.Claims;
using DemoWebsite.Models;
using DemoWebsite.Services;

namespace DemoWebsite.Controllers
{
    public class UserRegistrationsController : Controller
    {
        public IUserService userService; 
        public ICartService cartService;

        public UserRegistrationsController(IUserService user, ICartService cart)
        {
            userService = user;
            cartService = cart;
        }


        [HttpGet]
        public ActionResult Create()
        {
            Session["HomePage"] = null;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(UserRegistration model)
        {
            #region Count the Cart Items

            //var session = System.Web.HttpContext.Current.Session;
            //int authenticateUserID = 0;
            //if (SessionUtilities.GetAuthenticatedUserId() == 0)
            //{
            //    session["CartItems"] = cartService.GetCartItems().Where(a => a.Status == "Pending" || a.Status == "NULL").Distinct().Count();
            //}
            //else
            //{
            //    authenticateUserID = SessionUtilities.GetAuthenticatedUserId();
            //    var userDetail = userService.GetUserDataByUserID(authenticateUserID);
            //    session["CartItems"] = cartService.GetCartItemsByEmailID(userDetail.Email).Where(a => a.Status == "Pending" || a.Status == "NULL").Distinct().Count();
            //}

            #endregion            



            if (ModelState.IsValid)
            {
                model.Role = "User";
                model.LastLogin = DateTime.Now;


                model.Status = "Active";       
                var updated = await userService.SaveData(model);
            if (updated.Exceptions.Any())
            {
                var excpetionMessage = updated.Exceptions.ToList();
                foreach (var ex in excpetionMessage)
                {
                    if (ex.Value == "First Name should not be Empty")
                    {
                        TempData["Error"] = ex.Value;
                        return View(model);
                    }
                    else if (ex.Value == "Last Name should not be Empty")
                    {
                        TempData["Error"] = ex.Value;
                        return View(model);
                    }
                    else if (ex.Key == "FieldSame")
                    {
                        TempData["Error"] = ex.Value;
                        return View(model);
                    }
                }
                    TempData["Error"] = "Email/Phone Number already exists";
                    return View(model);
            }
            if (updated.Response == false)
            {
                TempData["Error"] = "Email/Phone Number already exists";                    
                return View(model);
            }

            UserRegistration vmLogin = new UserRegistration();
            vmLogin.Email = model.Email;
            vmLogin.Password = model.Password;

            var response = userService.CheckLogin(vmLogin);
            if (response.Response != null)
            {
                var identity = new ClaimsIdentity(new[]
                {
                    new Claim(ClaimTypes.Sid, Convert.ToString(response.Response.UserId)),
                    new Claim(ClaimTypes.Name, response.Response.FirstName+" "+response.Response.LastName),
                    new Claim(ClaimTypes.Email, response.Response.Email),
                    new Claim(ClaimTypes.Role, response.Response.Role),
                    new Claim(ClaimTypes.NameIdentifier, Convert.ToString(response.Response.UserId))
                    }, "ApplicationCookie");

                var ctx = Request.GetOwinContext();
                var authManager = ctx.Authentication;
                authManager.SignIn(identity);
                if (vmLogin.RememberMe)
                {
                    HttpCookie cookie = new HttpCookie("iShopUserLogin");
                    cookie.Values.Add("userEmail", vmLogin.Email);
                    cookie.Expires = DateTime.Now.AddDays(15);
                    Response.Cookies.Add(cookie);
                }
                    cartService.updateCartDataInDb(model.Email);
                    //LoginHistoryService.InsertLoginHistory(Convert.ToString(response.Response.UserId), iShop.Models.CommonEnums.UserType.User);
                    return Redirect(GetRedirectUrl(null));
                    
                }
               
            }
            else
           {
                    return Redirect(GetRedirectLoginUrl(null));
           }

           
            return View("Create", model);

    }
    private string GetRedirectUrl(string returnUrl)
    {
        if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
        {
            return Url.Action("Index", "Home");
        }

        return returnUrl;
    }
        private string GetRedirectLoginUrl(string returnUrl)
        {
            if (string.IsNullOrEmpty(returnUrl) || !Url.IsLocalUrl(returnUrl))
            {
                return Url.Action("Login", "UsersLogin");
            }

            return returnUrl;
        }
    }
}

DemoWebsite/Views/UserRegistrations/Create.cshtml
@model DemoWebsite.Models.UserRegistration

<style>
	.error{
		font-size:13px;
        margin-left:10px;
	}
</style>


@using (Html.BeginForm("Create", "UserRegistrations", FormMethod.Post, new { id = "registerForm" }))
{
    <div class="rest-body">
        @Html.Partial("_Registration", Model)
    </div>
}

DemoWebsite/Views/UserRegistrations/_Registration.cshtml
@model DemoWebsite.Models.UserRegistration

@Html.AntiForgeryToken()


<div class="container">
    <fieldset>
        <legend>Register</legend>
    </fieldset>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">                
                <label for="firstName">First Name<span>@ViewData["FirstName"]</span></label>                
                @Html.EditorFor(model => model.FirstName, "", new { htmlAttributes = new { @placeholder = "First Name", @class="form-control" , id = "firstName", tabindex = "1", required = "required" } })
            </div>
            <div class="form-group">
                <label for="email">Email Address<span>@Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger error" })</span></label>
                @Html.EditorFor(model => model.Email, "", new { htmlAttributes = new { @placeholder = "Email Address", @class = "form-control", id = "email" , tabindex = "3",type="email", required = "required" } })
                @*<input type="email" class="form-control" id="email"  placeholder="Email Address">*@
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <div class="form-group">
                <label for="contact">Contact No.<span>@Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger error" })</span></label>
                @Html.EditorFor(model => model.PhoneNumber, "", new { htmlAttributes = new { @placeholder = "Contact Number", @class = "form-control", id = "contact" , tabindex = "5",type="tel", required = "required" } })
                @*<input type="text" class="form-control" id="contact" aria-describedby="contactHelp" placeholder="Contact Number">*@
                <small id="contactHelp" class="form-text text-muted">We'll send OTP to this number for verification.</small>
            </div>          
        </div>
        <div class="col-md-6">
            <div class="form-group">
                <label for="lastName">Last Name<span>@ViewData["LastName"]</span></label>
                @Html.EditorFor(model => model.LastName, "", new { htmlAttributes = new { @placeholder = "Last Name", @class = "form-control", id = "lastName" , tabindex = "2" , required = "required" } })
            </div>
            <div class="form-group">
                <label for="InputPassword">Password<span>@Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger error" })</span></label>
                @Html.EditorFor(model => model.Password, "", new { htmlAttributes = new { @placeholder = "Password", @class = "form-control", id = "InputPassword" ,type = "password" , tabindex = "4" , required = "required" } })
                @*<input type="password" class="form-control" id="InputPassword" placeholder="Password">*@
            </div>                        
        </div>
     </div>    
    <button type="submit" class="btn btn-primary" tabindex="6">Submit</button><br>
    <span>Already Registered? <a href="@Url.Action("Login","UsersLogin")">Login Here</a></span>
</div>

<div id="snackbar" style="background-color: #F00;">Product added in cart..</div>

@if (TempData["Error"] != null)
{
    <script type="text/javascript">
        var messageForSnackBar = "@TempData["Error"]";
        $("#snackbar").text(messageForSnackBar);
        $("#snackbar").addClass("show");
        setTimeout(function () {
            $("#snackbar").removeClass("show");
        }, 9000);
    </script>
}